# Generated by Django 3.1.6 on 2022-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_whatwearereading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatwearereading',
            options={'verbose_name': 'What We Are Reading Link'},
        ),
        migrations.AddField(
            model_name='whatwearereading',
            name='site_id',
            field=models.IntegerField(default=999),
        ),
    ]
