# Generated by Django 3.1.6 on 2022-06-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20220622_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwearereading',
            name='site_id',
        ),
    ]
