# Generated by Django 3.1.6 on 2022-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_whatwearereading_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwearereading',
            name='site_id',
            field=models.IntegerField(default=999),
        ),
    ]
