# Generated by Django 3.1.6 on 2022-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_whatwearereading_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeAreReadingLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwar_link', models.URLField(verbose_name='Wwarlink:')),
            ],
            options={
                'verbose_name': 'News Post WWAR Links',
            },
        ),
    ]
