# Generated by Django 3.1.6 on 2022-06-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_whatwearereading_news_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwearereading',
            name='news_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newspost'),
        ),
    ]
