# Generated by Django 3.1.6 on 2022-06-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20220627_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatWeAreReadingLink',
        ),
    ]
