# Generated by Django 3.1.6 on 2022-06-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_whatwearereadinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwearereadinglink',
            name='news_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newspost'),
        ),
    ]
