# Generated by Django 3.1.6 on 2022-06-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20220628_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwearereading',
            name='news_post',
        ),
        migrations.AddField(
            model_name='newspost',
            name='wwar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.whatwearereading'),
        ),
    ]
