# Generated by Django 3.1.6 on 2022-06-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20220630_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='wwar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.whatwearereading'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='wwar_link',
            field=models.ManyToManyField(blank=True, related_name='wwar_link', to='news.WhatWeAreReading'),
        ),
    ]
